<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paraba.DAL\Paraba.DAL.csproj" />
    <ProjectReference Include="..\Paraba.ENTITY\Paraba.ENTITY.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Validations\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
